version: "3.7"

services:
  fhirDB:
    build:
      context: ./fhirDB
    image: leblancisc/covid-19-challenge:fhir_DB
    command: --key /irislicense/iris.key -a /IAM/load_swagger_specs.sh
    hostname: fhirDB
    restart: on-failure
    init: true
    ports:
      - "9089:51773" # 51773 is the superserver default port
      - "9088:52773" # 52773 is the webserver/management portal port
    volumes:
      - type: bind
        source: ./IRISLicense/
        target: /irislicense

  iam-migrations:
    image: leblancisc/covid-19-challenge:iam.IAM-stable
    command: kong migrations up
    depends_on:
      - db
      - fhirDB
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-iam}
      KONG_PG_HOST: db
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-iam}
      KONG_PG_USER: ${KONG_PG_USER:-iam}
      KONG_CASSANDRA_CONTACT_POINTS: db
      ISC_IRIS_URL: "http://IAM:sys@fhirDB:52773/api/iam/license"
    restart: on-failure
    links:
      - db:db

  iam:
    image: leblancisc/covid-19-challenge:iam.IAM-stable
    hostname: iam
    depends_on:
      - db
      - fhirDB
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ANONYMOUS_REPORTS: "off"
      KONG_CASSANDRA_CONTACT_POINTS: db
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-iam}
      KONG_PG_HOST: db
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-iam}
      KONG_PG_USER: ${KONG_PG_USER:-iam}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PORTAL: "on"
      KONG_PORTAL_GUI_PROTOCOL: http
      KONG_PORTAL_GUI_HOST: "localhost:8003"
      ISC_IRIS_URL: "http://IAM:sys@fhirDB:52773/api/iam/license"
    links:
      - db:db
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
      - target: 8001
        published: 8001
        protocol: tcp
      - target: 8002
        published: 8002
        protocol: tcp
      - target: 8003
        published: 8003
        protocol: tcp
      - target: 8004
        published: 8004
        protocol: tcp
      - target: 8443
        published: 8443
        protocol: tcp
      - target: 8444
        published: 8444
        protocol: tcp
      - target: 8445
        published: 8445
        protocol: tcp
    restart: on-failure

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-iam}
      POSTGRES_PASSWORD: ${KONG_PG_PASSWORD:-iam}
      POSTGRES_USER: ${KONG_PG_USER:-iam}
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${KONG_PG_USER:-iam}"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    stdin_open: true
    tty: true


volumes:
  pgdata:
